[project]
name = "mcp-data-handles-demo"
version = "0.1.0"
description = "Demo of working with data using handles in MCP"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "mcp[cli]>=1.6.0",
    "pandas>=2.2.3",
]
